### ISSUE TITLE
Create Article content type

### ISSUE THREAD

**Issue by amitaibu** [ItamarGronich/jekyll-task#2]
* Title, Image, Body
* Reference to `Vehicle`
* Status (pending, accepted, rejected)

**Comment by ItamarGronich** [comment]
Done

Provided screenshots 


![ford-article](https://cloud.githubusercontent.com/assets/14963977/16038584/5d901d98-322e-11e6-8481-e182bdc6dd4f.png)
![ford-article-view](https://cloud.githubusercontent.com/assets/14963977/16038585/5d919146-322e-11e6-929b-b95ea2c97864.png)
